### ISSUE TITLE
Consider options for a backend

### ISSUE THREAD

**Issue by trailofdad** [trailofdad/straylight-wiki#2]
Do we need a backend for this at all, or would we be happy dropping committing a markdown file to github to make a post?

We could use the Wordpress api and keep our current instance up and draw our data from that.

Contentful (https://www.contentful.com/) Their free tier would probably be fine IIRC and we wouldn't have to manage it ourselves.

**Comment by dougestey** [comment]
I think we're fine to kick this can down the road. Launch with bare content, deal with a backend for a wiki & OAuth.
